/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package customer;
import config.Koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
/**
 *
 * @author lenovo
 */
public class DataTersedia extends javax.swing.JPanel {

    /**
     * Creates new form DataTersedia
     */
    
    private MainCustomer parent;
    private int selectedIdTiket;
    
    public DataTersedia(MainCustomer parent) {
        this.parent = parent;
        initComponents();
        takeOff.addActionListener(e -> autoLoad());
        landing.addActionListener(e -> autoLoad());
        date.addPropertyChangeListener("date", e -> autoLoad());

        loadTiket();
    }
    
    private void loadBandara() {
        try {
            Connection conn = Koneksi.getKoneksi();
            String sql = "SELECT lokasi_bandara FROM bandara";
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            takeOff.removeAllItems();
            landing.removeAllItems();

            while (rs.next()) {
                String kota = rs.getString("lokasi_bandara");
                takeOff.addItem(kota);
                landing.addItem(kota);
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Gagal load data bandara");
            e.printStackTrace();
        }
    }
    
    public void loadFromParent() {
        // Ambil data dari MainCustomer
        takeOff.setSelectedItem(parent.getAsal());
        landing.setSelectedItem(parent.getTujuan());
        date.setDate(parent.getTanggal());

        loadTiket(); 
    }
    
    private void loadTiket() {
        try {
            Connection conn = Koneksi.getKoneksi();

            String sql = """
                SELECT t.id_tiket, t.kelas, t.harga,
                       j.tanggal_berangkat, j.waktu_berangkat, j.waktu_tiba,
                       ba.nama_bandara AS asal,
                       bt.nama_bandara AS tujuan,
                       m.nama_maskapai
                FROM tiket t
                JOIN jadwal j ON t.id_jadwal = j.id_jadwal
                JOIN rute r ON j.id_rute = r.id_rute
                JOIN bandara ba ON r.id_bandara_asal = ba.id_bandara
                JOIN bandara bt ON r.id_bandara_tujuan = bt.id_bandara
                JOIN pesawat p ON j.id_pesawat = p.id_pesawat
                JOIN maskapai m ON p.id_maskapai = m.id_maskapai
                WHERE ba.nama_bandara = ?
                  AND bt.nama_bandara = ?
                  AND j.tanggal_berangkat = ?
                  AND t.status = 'Tersedia'
            """;

            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, parent.getAsal());
            ps.setString(2, parent.getTujuan());
            ps.setDate(3, new java.sql.Date(parent.getTanggal().getTime()));

            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                selectedIdTiket = rs.getInt("id_tiket");

                maskapai.setText(rs.getString("nama_maskapai"));
                kelas.setText(rs.getString("kelas"));

                takeOff1.setText(rs.getString("asal"));
                landing1.setText(rs.getString("tujuan"));

                takeOffDate1.setText(rs.getString("tanggal_berangkat"));
                landingDate1.setText(rs.getString("tanggal_berangkat"));

                takeOffTime1.setText(rs.getString("waktu_berangkat"));
                landingTime1.setText(rs.getString("waktu_tiba"));

                harga1.setText("Rp " + rs.getInt("harga") + " /person");
            } else {
                maskapai.setText("Tidak ada tiket tersedia");
                harga1.setText("-");
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Gagal mengambil data tiket");
            e.printStackTrace();
        }
    }
    
    private void autoLoad() {
        if (takeOff.getSelectedItem() == null ||
            landing.getSelectedItem() == null ||
            date.getDate() == null) {
            return;
        }

        if (takeOff.getSelectedItem()
            .equals(landing.getSelectedItem())) {
            return;
        }

        loadJadwal();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        takeOff = new javax.swing.JComboBox<>();
        landing = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        date = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jadwal = new javax.swing.JPanel();
        maskapai = new javax.swing.JLabel();
        kelas = new javax.swing.JLabel();
        takeOff1 = new javax.swing.JLabel();
        takeOffDate1 = new javax.swing.JLabel();
        takeOffTime1 = new javax.swing.JLabel();
        landing1 = new javax.swing.JLabel();
        landingDate1 = new javax.swing.JLabel();
        landingTime1 = new javax.swing.JLabel();
        harga1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Choose");

        jPanel1.setBackground(new java.awt.Color(32, 173, 212));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Landing");

        takeOff.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bali", "Jakarta" }));

        landing.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jakarta", "Bali" }));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Take Off");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Take Off Date");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(takeOff, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(landing, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(takeOff, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(landing, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(32, 173, 212));

        jadwal.setBackground(new java.awt.Color(130, 205, 252));
        jadwal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jadwalMouseClicked(evt);
            }
        });

        maskapai.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        maskapai.setText("LION AIR");

        kelas.setText("Economy");

        takeOff1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        takeOff1.setText("Bali");

        takeOffDate1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        takeOffDate1.setText("Wed, 30 Sep 2022");

        takeOffTime1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        takeOffTime1.setText("17.00");

        landing1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        landing1.setText("Jakarta");

        landingDate1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        landingDate1.setText("Wed, 30 Sep 2022");

        landingTime1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        landingTime1.setText("19.10");

        harga1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        harga1.setText("Rp. 1.030.000 -/person");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel13.setText("Direct");

        javax.swing.GroupLayout jadwalLayout = new javax.swing.GroupLayout(jadwal);
        jadwal.setLayout(jadwalLayout);
        jadwalLayout.setHorizontalGroup(
            jadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jadwalLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maskapai)
                    .addComponent(kelas))
                .addGap(109, 109, 109)
                .addGroup(jadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(takeOffDate1)
                    .addGroup(jadwalLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(takeOff1))
                    .addGroup(jadwalLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(takeOffTime1)))
                .addGroup(jadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jadwalLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(landingDate1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(harga1)
                        .addGap(42, 42, 42))
                    .addGroup(jadwalLayout.createSequentialGroup()
                        .addGroup(jadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jadwalLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel13)
                                .addGap(70, 70, 70)
                                .addComponent(landingTime1))
                            .addGroup(jadwalLayout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addComponent(landing1)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jadwalLayout.setVerticalGroup(
            jadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jadwalLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jadwalLayout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addGroup(jadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jadwalLayout.createSequentialGroup()
                                    .addGroup(jadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(landingDate1)
                                        .addComponent(harga1))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(landingTime1))
                                .addGroup(jadwalLayout.createSequentialGroup()
                                    .addGroup(jadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(takeOff1)
                                        .addComponent(landing1))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(takeOffDate1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(takeOffTime1)))
                            .addContainerGap(35, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jadwalLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addGap(0, 19, Short.MAX_VALUE)))
                    .addGroup(jadwalLayout.createSequentialGroup()
                        .addComponent(maskapai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kelas)
                        .addContainerGap())))
        );

        jPanel4.setBackground(new java.awt.Color(130, 205, 252));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("SINGAPORE AIRLINES");

        jLabel16.setText("Bussines Class");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel17.setText("Bali");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel18.setText("Wed, 30 Sep 2022");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel19.setText("10.00");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel20.setText("Jakarta");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel21.setText("Wed, 30 Sep 2022");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel22.setText("12.10");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel23.setText("Direct");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setText("Rp. 1.330.000 -/person");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(41, 41, 41)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel17))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel19)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel20))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel23)
                        .addGap(70, 70, 70)
                        .addComponent(jLabel22))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel21)))
                .addGap(47, 47, 47)
                .addComponent(jLabel24)
                .addGap(72, 72, 72))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel22))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel19)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel23)))
                        .addGap(0, 15, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel24))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jadwal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jadwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addComponent(jLabel1)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jadwalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jadwalMouseClicked
        // TODO add your handling code here:
        parent.setIdTiketDipilih(selectedIdTiket);
        parent.showPanel(parent.getPanelDetailPesanan());
    }//GEN-LAST:event_jadwalMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JLabel harga1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jadwal;
    private javax.swing.JLabel kelas;
    private javax.swing.JComboBox<String> landing;
    private javax.swing.JLabel landing1;
    private javax.swing.JLabel landingDate1;
    private javax.swing.JLabel landingTime1;
    private javax.swing.JLabel maskapai;
    private javax.swing.JComboBox<String> takeOff;
    private javax.swing.JLabel takeOff1;
    private javax.swing.JLabel takeOffDate1;
    private javax.swing.JLabel takeOffTime1;
    // End of variables declaration//GEN-END:variables
}
