/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package customer;

import config.Koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lenovo
 */
public class DataTersedia extends javax.swing.JPanel {

    /**
     * Creates new form DataTersedia
     */
    
    private MainCustomer parent;
    private int selectedIdTiket = -1;
    
    public DataTersedia(MainCustomer parent) {
        this.parent = parent;
        initComponents();
    }
    
    
    
    public void loadData() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // bersihkan tabel

        try {
            Connection conn = Koneksi.getKoneksi();

            PreparedStatement ps = conn.prepareStatement("""
                SELECT
                      t.id_tiket,
                      j.id_jadwal,
                      m.nama_maskapai,
                      t.kelas,
                      b1.nama_bandara AS asal,
                      b2.nama_bandara AS tujuan,
                      j.tanggal_berangkat,
                      j.tanggal_tiba,
                      j.waktu_berangkat,
                      j.waktu_tiba,
                      t.harga
                  FROM tiket t
                  JOIN jadwal j ON t.id_jadwal = j.id_jadwal
                  JOIN rute r ON j.id_rute = r.id_rute
                  JOIN bandara b1 ON r.id_bandara_asal = b1.id_bandara
                  JOIN bandara b2 ON r.id_bandara_tujuan = b2.id_bandara
                  JOIN pesawat p ON j.id_pesawat = p.id_pesawat
                  JOIN maskapai m ON p.id_maskapai = m.id_maskapai
                  WHERE r.id_bandara_asal = ?
                    AND r.id_bandara_tujuan = ?
                    AND j.tanggal_berangkat = ?
                    AND t.status = 'Tersedia'
            """);

            ps.setInt(1, parent.getIdBandaraAsal());
            ps.setInt(2, parent.getIdBandaraTujuan());
            ps.setDate(3, new java.sql.Date(parent.getTanggalBerangkat().getTime()));

            ResultSet rs = ps.executeQuery();

            boolean adaData = false;

            while (rs.next()) {
                adaData = true;

                model.addRow(new Object[] {
                    rs.getInt("id_tiket"),
                    rs.getString("nama_maskapai"),
                    rs.getString("kelas"),
                    rs.getString("asal"),
                    rs.getString("tujuan"),
                    rs.getDate("tanggal_berangkat"),
                    rs.getDate("tanggal_tiba"),
                    rs.getTime("waktu_berangkat"),
                    rs.getTime("waktu_tiba"),
                    rs.getInt("harga"),
                    "Pilih"
                });
            }

            if (!adaData) {
                JOptionPane.showMessageDialog(this, "Jadwal tidak ditemukan");
            }

            rs.close();
            ps.close();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal memuat jadwal");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Choose");

        jPanel2.setBackground(new java.awt.Color(32, 173, 212));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Maskapai", "Class", "Take Off", "Landing", "Flight Date", "Landing Date", "Flight Time", "Landing Time", "Price"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addComponent(jLabel1)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        if (row < 0) return;
        
        selectedIdTiket = Integer.parseInt(
            jTable1.getValueAt(row, 0).toString()
        );

        // ambil data dari tabel (sesuai urutan kolommu)
        String maskapai = jTable1.getValueAt(row, 1).toString();
        String kelas = jTable1.getValueAt(row, 2).toString();
        String asal = jTable1.getValueAt(row, 3).toString();
        String tujuan = jTable1.getValueAt(row, 4).toString();
        Object tglBerangkat = jTable1.getValueAt(row, 5);
        Object tglTiba = jTable1.getValueAt(row, 6);
        Object jamBerangkat = jTable1.getValueAt(row, 7);
        Object jamTiba = jTable1.getValueAt(row, 8);
        int harga = Integer.parseInt(jTable1.getValueAt(row, 9).toString());
        
        // kirim ke DetailPesanan
        DetailPesanan dp = parent.getPanelDetailPesanan();
        
        dp.setDataFromTable(
            maskapai, kelas, asal, tujuan,
            tglBerangkat, tglTiba,
            jamBerangkat, jamTiba,
            harga,
            selectedIdTiket
        );

        parent.showPanel(parent.getPanelDetailPesanan());
        dp.loadUserData();

        parent.showPanel(dp);
        
        
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
