/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package customer;
import config.Koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author lenovo
 */
public class DetailPesanan extends javax.swing.JPanel {

    /**
     * Creates new form DetailPesanan
     */
    
    private MainCustomer parent;
    private int idTiket;
    private int idPelanggan;
    
    
    public DetailPesanan(MainCustomer parent) {
        this.parent = parent;
        initComponents();
    }
    
    public void setDataFromTable(
            String maskapai,
            String kelas,
            String asal,
            String tujuan,
            Object tglBerangkat,
            Object tglTiba,
            Object jamBerangkat,
            Object jamTiba,
            int harga,
            int idTiket) {

        this.idTiket = idTiket;
        
        this.maskapai.setText(maskapai);
        this.kelas.setText(kelas);
        this.takeOff.setText(asal);
        this.landing.setText(tujuan);

        this.takeOffDate.setText(tglBerangkat.toString());
        this.landingDate.setText(tglTiba.toString());
        this.takeOffTime.setText(jamBerangkat.toString());
        this.landingTime.setText(jamTiba.toString());

        this.harga.setText("Rp " + String.format("%,d", harga));
    }
    
    public void loadUserData() {
        nama.setText(parent.getNamaUser());
        email.setText(parent.getEmailUser());
        no_hp.setText(parent.getHpUser());
        alamat.setText(parent.getAlamatUser());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        harga = new javax.swing.JLabel();
        maskapai = new javax.swing.JLabel();
        kelas = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        takeOff = new javax.swing.JLabel();
        landing = new javax.swing.JLabel();
        takeOffDate = new javax.swing.JLabel();
        takeOffTime = new javax.swing.JLabel();
        landingDate = new javax.swing.JLabel();
        landingTime = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        no_hp = new javax.swing.JLabel();
        alamat = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Details");

        jPanel1.setBackground(new java.awt.Color(32, 173, 212));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setText("Make order");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(130, 205, 252));

        harga.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        harga.setText("Rp. 1.030.000 -/person");

        maskapai.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        maskapai.setText("LION AIR");

        kelas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        kelas.setText("Economy");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("To");

        takeOff.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        takeOff.setText("Bali");

        landing.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        landing.setText("Jakarta");

        takeOffDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        takeOffDate.setText("Wed, 30 Sep 2022");

        takeOffTime.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        takeOffTime.setText("17.00");

        landingDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        landingDate.setText("Wed, 30 Sep 2022");

        landingTime.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        landingTime.setText("19.10");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(kelas))
                    .addComponent(maskapai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(takeOffDate)
                    .addComponent(takeOff)
                    .addComponent(takeOffTime))
                .addGap(40, 40, 40)
                .addComponent(jLabel15)
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(landingDate)
                    .addComponent(landing)
                    .addComponent(landingTime))
                .addGap(55, 55, 55)
                .addComponent(harga)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(harga)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(22, 22, 22))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(maskapai)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(kelas))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(takeOff)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(takeOffDate)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(takeOffTime)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(landing)
                                .addGap(44, 44, 44))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(landingDate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(landingTime)))
                        .addContainerGap())))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Full Name");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Phone Number");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Address");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(": ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(": ");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText(": ");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText(": ");

        nama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nama.setForeground(new java.awt.Color(255, 255, 255));
        nama.setText("Gede Bayu Wardhana");

        email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setText("debay@gmail.com");

        no_hp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        no_hp.setForeground(new java.awt.Color(255, 255, 255));
        no_hp.setText("08123456789");

        alamat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        alamat.setForeground(new java.awt.Color(255, 255, 255));
        alamat.setText("Jimbaran, Kuta Selatan, Badung, Bali, Indonesia");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(283, 283, 283))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alamat))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(no_hp))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(email))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nama)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(no_hp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alamat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(369, 369, 369)
                .addComponent(jLabel1)
                .addContainerGap(375, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        Connection conn = null;
        
        System.out.println("===== DEBUG ORDER =====");
        System.out.println("ID USER     : " + parent.getIdUserLogin());
        System.out.println("Nama        : " + nama.getText());
        System.out.println("Email       : " + email.getText());
        System.out.println("HP          : " + no_hp.getText());
        System.out.println("Alamat      : " + alamat.getText());
        System.out.println("ID Tiket    : " + idTiket);
        System.out.println("=======================");

        try {
            conn = Koneksi.getKoneksi();
            conn.setAutoCommit(false); // transaksi aman

            // Insert/ ambil Id Pelanggan
            String sqlPelanggan = """
                INSERT INTO pelanggan (id_user, nama_lengkap, email, no_hp, alamat)
                VALUES (?, ?, ?, ?, ?)
            """;

            PreparedStatement psPelanggan =
                    conn.prepareStatement(sqlPelanggan, PreparedStatement.RETURN_GENERATED_KEYS);

            psPelanggan.setInt(1, parent.getIdUserLogin()); // dari login
            psPelanggan.setString(2, nama.getText());
            psPelanggan.setString(3, email.getText());
            psPelanggan.setString(4, no_hp.getText());
            psPelanggan.setString(5, alamat.getText());

            psPelanggan.executeUpdate();

            ResultSet rsPelanggan = psPelanggan.getGeneratedKeys();
            if (rsPelanggan.next()) {
                idPelanggan = rsPelanggan.getInt(1);
            }
            
            // Insert Pemesanan
            String sqlPemesanan = """
                INSERT INTO pemesanan
                (id_pelanggan, id_tiket, tanggal_pemesanan, status_pemesanan)
                VALUES (?, ?, NOW(), 'Menunggu')
            """;

            PreparedStatement psPemesanan =
                    conn.prepareStatement(sqlPemesanan, PreparedStatement.RETURN_GENERATED_KEYS);

            psPemesanan.setInt(1, idPelanggan);
            psPemesanan.setInt(2, idTiket);

            psPemesanan.executeUpdate();

            ResultSet rsPemesanan = psPemesanan.getGeneratedKeys();
            int idPemesanan = 0;
            if (rsPemesanan.next()) {
                idPemesanan = rsPemesanan.getInt(1);
            }
            
            // Update status tiket
            String sqlUpdateTiket =
                    "UPDATE tiket SET status = 'Dipesan' WHERE id_tiket = ?";

            PreparedStatement psUpdate = conn.prepareStatement(sqlUpdateTiket);
            psUpdate.setInt(1, idTiket);
            psUpdate.executeUpdate();

            conn.commit();

            JOptionPane.showMessageDialog(this, "Pemesanan berhasil!");
            
            // Pindah ke Pembayaran
            Pembayaran pb = parent.getPanelPembayaran();
            pb.setDataFromPemesanan(
                maskapai.getText(),
                kelas.getText(),
                takeOff.getText(),
                landing.getText(),
                takeOffDate.getText(),
                takeOffTime.getText(),
                landingDate.getText(),
                landingTime.getText(),
                harga.getText(),
                idPemesanan
            );

            parent.showPanel(pb);

        } catch (Exception e) {
            try {
                if (conn != null) conn.rollback();
            } catch (Exception ex) {
                ex.printStackTrace();
            }
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal menyimpan pemesanan");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamat;
    private javax.swing.JLabel email;
    private javax.swing.JLabel harga;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel kelas;
    private javax.swing.JLabel landing;
    private javax.swing.JLabel landingDate;
    private javax.swing.JLabel landingTime;
    private javax.swing.JLabel maskapai;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel no_hp;
    private javax.swing.JLabel takeOff;
    private javax.swing.JLabel takeOffDate;
    private javax.swing.JLabel takeOffTime;
    // End of variables declaration//GEN-END:variables
}
