/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package customer;

import config.Koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author lenovo
 */



public class Pembayaran extends javax.swing.JPanel {

    /**
     * Creates new form Pembayaran
     */
    
    private MainCustomer parent;
    private int idPemesanan;
    
    public Pembayaran(MainCustomer parent) {
        this.parent = parent;
        initComponents();
    }
    
    public void setDataFromPemesanan(
            String maskapai,
            String kelas,
            String asal,
            String tujuan,
            String tglBerangkat,
            String jamBerangkat,
            String tglTiba,
            String jamTiba,
            String harga,
            int idPemesanan) {

        this.idPemesanan = idPemesanan;

        this.maskapai.setText(maskapai);
        this.kelas.setText(kelas);
        this.takeOff.setText(asal);
        this.landing.setText(tujuan);
        this.takeOffDate.setText(tglBerangkat);
        this.takeOffTime.setText(jamBerangkat);
        this.landingDate.setText(tglTiba);
        this.landingTime.setText(jamTiba);
        this.harga.setText(harga);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        harga = new javax.swing.JLabel();
        maskapai = new javax.swing.JLabel();
        kelas = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        takeOff = new javax.swing.JLabel();
        landing = new javax.swing.JLabel();
        takeOffDate = new javax.swing.JLabel();
        takeOffTime = new javax.swing.JLabel();
        landingDate = new javax.swing.JLabel();
        landingTime = new javax.swing.JLabel();
        harga1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Payment");

        jPanel1.setBackground(new java.awt.Color(32, 173, 212));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setText("Pay");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(130, 205, 252));

        harga.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        harga.setText("Rp. 1.030.000 -/person");

        maskapai.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        maskapai.setText("LION AIR");

        kelas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        kelas.setText("Economy");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("To");

        takeOff.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        takeOff.setText("Bali");

        landing.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        landing.setText("Jakarta");

        takeOffDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        takeOffDate.setText("Wed, 30 Sep 2022");

        takeOffTime.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        takeOffTime.setText("17.00");

        landingDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        landingDate.setText("Wed, 30 Sep 2022");

        landingTime.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        landingTime.setText("19.10");

        harga1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        harga1.setText("Total Payment");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(kelas))
                    .addComponent(maskapai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(takeOffDate)
                    .addComponent(takeOff)
                    .addComponent(takeOffTime))
                .addGap(44, 44, 44)
                .addComponent(jLabel15)
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(landingDate)
                    .addComponent(landing)
                    .addComponent(landingTime))
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(harga1)
                    .addComponent(harga))
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(maskapai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kelas))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(takeOff)
                                .addComponent(landing))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(takeOffDate)
                                .addComponent(jLabel15)
                                .addComponent(landingDate))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(landingTime))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(harga1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(harga)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(takeOffTime))))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(328, 328, 328)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jButton1)
                .addGap(64, 64, 64))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(357, 357, 357)
                        .addComponent(jLabel1)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Connection conn = null;

        System.out.println("ID PEMESANAN (PAY): " + idPemesanan);
        try {
            conn = Koneksi.getKoneksi();

            String sql = """
                UPDATE pemesanan
                SET status_pemesanan = 'Sudah Dibayar'
                WHERE id_pemesanan = ?
            """;

            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, idPemesanan);
            ps.executeUpdate();

            JOptionPane.showMessageDialog(this, "Pembayaran berhasil!");

            // kembali ke menu awal
            parent.showHome();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal memproses pembayaran");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel harga;
    private javax.swing.JLabel harga1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel kelas;
    private javax.swing.JLabel landing;
    private javax.swing.JLabel landingDate;
    private javax.swing.JLabel landingTime;
    private javax.swing.JLabel maskapai;
    private javax.swing.JLabel takeOff;
    private javax.swing.JLabel takeOffDate;
    private javax.swing.JLabel takeOffTime;
    // End of variables declaration//GEN-END:variables
}
